version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0

references:
  js_deps_cache_key: &js_deps_cache_key v1-dependency-{{ checksum "package-lock.json" }}
  js_deps_backup_key: &js_deps_backup_key v1-dependency-

master_only: &master_only
  filters:
    branches:
      only: master
ignore_gh_pages: &ignore_gh_pages
  filters:
    branches:
      ignore: gh-pages
release_tags_only: &release_tags_only
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/
commands:
  git_authoring:
    description: Authoring git commit.
    steps:
      - run: git config --global push.default matching
      - run: git config --global user.email "totem-bot@darteaga.com"
      - run: git config --global user.name "Totem Bot"

jobs:
  build:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_key
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key

  test:
    docker:
      - image: cimg/node:18.12
    environment:
      NODE_ENV: ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_key
      - run: npm test

  release:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - git_authoring
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_key
      - run: ./.circleci/skip-when-release npm run release

  deploy:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - aws-s3/sync:
          from: templates
          to: "s3://stable-seeds/code-quality/templates"
          arguments: |
            --acl public-read
      - aws-s3/copy:
          from: seed.yaml
          to: "s3://stable-seeds/code-quality/seed.yaml"
          arguments: |
            --acl public-read

workflows:
  version: 2
  default:
    jobs:
      - build:
          <<: *ignore_gh_pages
      - test:
          <<: *ignore_gh_pages
          requires:
            - build
      - release:
          <<: *master_only
          requires:
            - test
  delivering:
    jobs:
      - deploy:
          <<: *release_tags_only
