{{#if deployment.enabled}}
{{#if deployment.type "===" "chart"}}
chart-dirs:
  - {{deployment.chart.root}}
chart-repos:
  - {{artifact}}-chart=https://dani8art.github.io/{{artifact}}-chart
  {{#each deployment.chart.additionalRepos}}
  - {{this.name}}={{this.url}}
  {{/each}}
check-version-increment: false
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
{{/if}}
{{/if}}