version: 2.1
{{#if deployment.enabled}}
{{#with deployment.s3}}
orbs:
  aws-s3: circleci/aws-s3@3.0
{{/with}}
{{/if}}

references:
  js_deps_cache_key: &js_deps_cache_key v1-dependency-\{{ checksum "package-lock.json" }}
  js_deps_backup_key: &js_deps_backup_key v1-dependency-

master_only: &master_only
  filters:
    branches:
      only: master
ignore_gh_pages: &ignore_gh_pages
  filters:
    branches:
      ignore: gh-pages
release_tags_only: &release_tags_only
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/
commands:
  git_authoring:
    description: Authoring git commit.
    steps:
      - run: git config --global push.default matching
      - run: git config --global user.email "{{git.email}}"
      - run: git config --global user.name "{{git.name}}"

jobs:
  build:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_key
      - run: npm ci
      {{#with build}}
      {{#if cmd}}
      - run: {{cmd}}
      {{/if}}
      {{/with}}
      - save_cache:
          paths:
            {{#each cache}}
            - {{this}}
            {{/each}}
          key: *js_deps_cache_key

  test:
  {{#if deployment.type "===" "chart"}}
    docker:
      - image: docker.io/darteaga/seed-circleci
    steps:
      - checkout
      - run: ct lint --config .circleci/charts.config.yml
  {{else}}
    docker:
      - image: cimg/node:18.12
    {{#with test}}
    {{#each dependencies}}
      - image: {{this}}
    {{/each}}
    {{/with}}
    environment:
      NODE_ENV: ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_key
      {{#with test}}
      {{#if cmd}}
      - run: {{cmd}}
      {{else}}
      - run: npm test
      {{/if}}
      {{else}}
      - run: npm test
      {{/with}}
  {{/if}}

{{#if release.enabled}}
  release:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - git_authoring
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_key
      - run: ./.circleci/skip-when-release npm run release
{{/if}}

{{#if deployment.enabled}}
  deploy:
    docker:
    {{#if deployment.type "===" "chart"}}
      - image: docker.io/darteaga/seed-circleci
    {{else}}
      - image: cimg/node:18.12
    {{/if}}
    steps:
      - checkout
    {{#with deployment.docker}}
      - setup_remote_docker
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_key
      - run: |
        {{#if @root.release.enabled}}
          MAIN_TAG="$(npm run --silent get:version)"
        {{else}}
          MAIN_TAG="$CIRCLE_BRANCH"
        {{/if}}
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker build -t {{this.image}}:$MAIN_TAG .
          docker push {{this.image}}:$MAIN_TAG
        {{#each this.additionalTags}}
          docker tag {{@root.deployment.docker.image}}:$MAIN_TAG {{@root.deployment.docker.image}}:{{this}}
          docker push {{@root.deployment.docker.image}}:{{this}}
        {{/each}}
    {{/with}}
    {{#if deployment.type "===" "npm"}}
      - run:
          name: Authenticate against npm registry.
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run: npm publish
    {{/if}}
    {{#if deployment.type "===" "s3"}}
      - aws-s3/sync:
          from: {{deployment.s3.bucket}}
          to: "s3://stable-seeds/{{artifact}}/{{deployment.s3.bucket}}"
          arguments: |
            --acl public-read
      {{#each deployment.s3.files}}
      - aws-s3/copy:
          from: {{this}}
          to: "s3://stable-seeds/{{@root.artifact}}/{{this}}"
          arguments: |
            --acl public-read
      {{/each}}
    {{/if}}
    {{#if deployment.type "===" "chart"}}
      - git_authoring
      - run: ./.circleci/charts-publish
    {{/if}}
  {{#if deployment.type "===" "docker"}}
  {{#with deployment.docker.chart}}
  chart:
    docker:
      - image: docker.io/darteaga/seed-circleci
    steps:
      - checkout
      - git_authoring
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_key
      - run: |
          version="$(jq -r ".version" package.json)"
          ./.circleci/charts-upgrade-app "${version}"
  {{/with}}
  {{/if}}
{{/if}}

workflows:
  version: 2
  default:
    jobs:
      - build:
          <<: *ignore_gh_pages
      - test:
          <<: *ignore_gh_pages
          requires:
            - build
      {{#if release.enabled}}
      - release:
          <<: *master_only
          requires:
            - test
      {{/if}}
{{#if deployment.enabled}}
  delivering:
    jobs:
      - deploy:
          <<: *release_tags_only
  {{#if deployment.type "===" "docker"}}
  {{#with deployment.docker.chart}}
      - chart:
          <<: *release_tags_only
          requires:
            - deploy
  {{/with}}
  {{/if}}  
{{/if}}
